### ISSUE TITLE
what do you mean “Attention Mechanism”？

### ISSUE THREAD

**Issue by GusRoth** [rsinghal757/tgs-image-segmentation#1]
I want to know where you achieve this function and could you please tell me which paper raise this?

Do you have a blog to introduction for this code?

**Comment by GusRoth** [comment]
could you share the architecture image?

**Comment by rsinghal757** [comment]
Heyy... You can refer to this paper (https://arxiv.org/abs/1804.03999)... 
The paper also has a block diagram of the architecture...
Basically, instead of propagating features through skip connections directly, the authors have used Attention Gates which filter the features propagated...
In the code, you can refer to the Architechture.py file (AttnGatingBlock function)...

Sorry for the late response... :)
